### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by MiXeR54** [PassTheMayo/minecraft-server-util#50] opened 2021-07-10 08:31 UTC
**Describe the bug:**
Trying to ping ip list, near 100 ip's.
But catching error with app crash.
```
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 149.202.31.128:25565
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1132:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '149.202.31.128',
  port: 25565
}
```

**Code:**
```javascript
const ping = async () => {
  for (let i = start; i < end; i++) {
    let ip = ipInt(i).toIP();

    await util
      .status(ip, {
        port: 25565,
        enableSRV: true,
        timeout: 5000,
      })
      .then((response) => {
        console.log(response);
      })
      .catch((error) => {
        console.error(error);
      });
  }
};

ping();

```

**Expected behavior:**
Expected ping next ip without crashing app.

**Comment by alex-r89** [comment] 2021-07-31 11:33
Also experiencing this when pinging both an array of IP's, or a single incorrect IP.

For example, pinging a host like `google.com`, pinging a local ip like `127.0.0.1` or purposefully pining an incorrect port like pinging port `11111` when the server is running on `25565` will result in this unhandled error which will crash the application.

**Comment by loveGhb** [comment] 2021-08-09 03:12
![image](https://user-images.githubusercontent.com/21294689/128656732-35029e0e-8a63-45f4-8e54-0686db6a8c97.png)
Likewise!

**Comment by alex-r89** [comment] 2021-08-09 09:55
I have had this running for a week, pinging a number of servers and this package has crashed my express server 21 times in that time - 3 times a day on average. Unfortunately, as fantastic as this package is, I would say it's unusable in its current state.

I have spoken to Mayo about this, he is aware but is busy at the moment working on other things.

It may be worth using another package or doing what i'm doing which is running your instance inside [PM2](https://pm2.keymetrics.io/) if possible. PM2 will auto restarting my express server if this package crashes it. Although this doesn't completely solve it - i still see inconsistencies and crashing, its at least putting a band aid on it for now.

**Comment by loveGhb** [comment] 2021-08-09 13:22
> I have had this running for a week, pinging a number of servers and this package has crashed my express server 21 times in that time - 3 times a day on average. Unfortunately, as fantastic as this package is, I would say it's unusable in its current state.
> 
> I have spoken to Mayo about this, he is aware but is busy at the moment working on other things.
> 
> It may be worth using another package or doing what i'm doing which is running your instance inside [PM2](https://pm2.keymetrics.io/) if possible. PM2 will auto restarting my express server if this package crashes it. Although this doesn't completely solve it - i still see inconsistencies when pinging an array and crashing when pinging single offline ips, its at least putting a band aid on it for now.

Thank you, I am already thinking about using PM2 too. But this is more of a crutch, I agree.

Can you tell me another package for ping Minecraft servers with which there are no such problems?

**Comment by alex-r89** [comment] 2021-08-11 17:55
If you can put a bandaid on this for now, using PM2 or something similar, I would stick with this package.

Although this problem is annoying, this package for the most part is fantastic. There are others out there you could use but a lot of them come with their own problems or lack of features.

Hopefully @PassTheMayo is able to free up some time to fix these issues soon 🙂🤞

**Comment by PassTheMayo** [comment] 2021-08-12 06:43
I did some digging and was able to recreate this error but it was being caught by the `.catch()` statement every time. This doesn't appear to crash the app or prematurely exit in any way, even using the same IP address as the one shown by @loveGhb. I went ahead and released `3.5.3` which removed some possible race condition of the event handlers but it was very unlikely that would affect this issue.

**Comment by alex-r89** [comment] 2021-08-12 09:02
Hey @PassTheMayo, thanks very much for taking the time to investigate.

I went ahead and tested 3.5.3 and I am still seeing the crashing. It actually crashed instantly for me. Let me explain how I have this set up:

### Array of servers

I ping an array of servers, currently 30 servers but this is expected to increase to well over 100 within a few weeks. I do this in the following way:

```js
  let completed = 0

  await new Promise((resolve) => {
    for (const server of servers) {
      util
        .status(`${server.ip}`, { port: server.port, timeout: 1800 })
        .then(async (response) => {
          console.log(`[🏓 Success pinging ${server.ip}]`)
          try {
            // Code to store this response in a database
            console.log(`[✅ Success storing ping data for ${server.ip}]`)
          } catch {
            console.log(`[❌ Error storing ping data for ${server.ip}]`)
          }
        })
        .catch(async (error) => {
          console.log(`[👎 Error pinging ${server.ip}]`, error)
          try {
            // code to store null as the value in the database
            console.log(`[✅ Success storing failed ping data for ${server.ip}]`)
          } catch {
            console.log(`[❌ Error storing failed ping data for ${server.ip}]`)
          }
        })
        .finally(() => {
          completed++
          if (completed >= servers.length) resolve()
        })
    }
  })

  console.log(`➡️  COMPLETE`)

```
I then run this via [node-cron](https://www.npmjs.com/package/node-cron) every minute. I can send you that configuration on Discord if you'd like the full setup. If the job runs successfully, the ping for my 30 servers is completed in under 5 seconds.

When I watch this code run and watch for the console logs above, when I see the ```console.log(`[👎 Error pinging ${server.ip}]`, error)``` console log, sometimes (not always) I see this with the error `undefined`. 

I believe this `undefined ` is the reason for the crash. When I see this error as undefined, sometimes my server crashes straight away. But other times it does not and I will see the final complete console log. What I have found is that if I run this cron job every minute, within an hour it will have crashed - so its a fairly consistent issue (I ping 60 times an hour and always see a crash within an hour).  I have also tried reducing the node cron schedule to 5 minutes, this doesnt solve the problem.

### Single server

Its also worth mentioning that I can recreate this error by just pinging one server. I have this set up in the following configuration:

```js
        try {
          const ping = await util.status(`${formattedBody.ip}`, {
            port: 25565,
            timeout: 1500
          })

          res.status(200).json(ping)
        } catch (error) {
          res.status(404).json({ message: `Server: ${formattedBody.ip} Offline.` })
        }
```

This configuration is set to fire via an on click of a button, which calls an API endpoint (this code is in the endpoint). The button is rate limited by disabling the button if the call is being made. However if I keep pinging a server over and over by continually clicking the button,  I will eventually see the undefined error and eventually the server will crash, like in the array example. It doesnt seem to matter if this server is online or offline, however it will occur faster if I ping a server which is offline OR purposefully incorrect like pinging port `11111` when the server is running on `25565`.

I have tried to have a look at the code but to be honest it makes mostly no sense to me so apologies for not being able to point you closer to an issue. Let me know if you would like any further info on Discord.

**Comment by PassTheMayo** [comment] 2021-08-13 19:23
I still haven't been able to find the root cause of this issue, Node seems to be ignoring my `error` event handler entirely. I went ahead and applied a *bandaid* to the problem by using the `domain` module to catch the error. Please update to `3.6.0` and verify the issue is resolved.

**Comment by alex-r89** [comment] 2021-08-14 10:46
Hey @PassTheMayo, this seems to have worked for me locally - great work! I have had it running for 12 hours straight, pinging every 5 minutes via a cron job, and it hasn't crashed once.

I am going to push this to production now and see how it fairs. I will update this comment with the results.

Fingers crossed 🤞

**Comment by PassTheMayo** [comment] 2021-09-05 18:37
Awesome! I'll go ahead and close this issue now.

**Closed by PassTheMayo** 2021-09-05 18:37 UTC
Labels: bug, help wanted

**Comment by jojomatik** [comment] 2021-11-26 11:20
> I still haven't been able to find the root cause of this issue, Node seems to be ignoring my `error` event handler entirely. I went ahead and applied a _bandaid_ to the problem by using the `domain` module to catch the error. Please update to `3.6.0` and verify the issue is resolved. This isn't my ideal solution but it's the only working one considering the severity of this issue.

Hi @PassTheMayo, I was wondering if there are any plans to replace this _bandaid_ fix with a another fix or if the _bandaid_ is considered production ready? I've not had any issues since I updated `minecraft-server-utils`, so the fix does seem to work indeed.

The original issue seemed to come out of nowhere for me and I first noticed it two days ago in my dev environment even though I had not updated `minecraft-server-utils` for a long time before and used the same version in a production build that worked just fine. Is there any information why, how and when the bug was introduced?

**Comment by PassTheMayo** [comment] 2021-11-26 19:04
@jojomatik I'm still not aware of how the `undefined` bug was caused, but I am currently in the middle of rewriting the library and it has considerably improved the code, both in line count and error handling. It should be released pretty soon (within the next few days at most).
